config/routes.rb
Rails.application.routes.draw do

  root to: "public#landing"

  namespace :administration do
    get 'dashboard'
  end

  namespace :development do
    get 'dashboard'
  end

  get 'about', to: 'public#about'
  get 'careers', to: 'public#careers'
  get 'help', to: 'public#help'
  get 'landing', to: 'public#landing'
  get 'privacy_policy', to: 'public#privacy_policy'
  get 'sitemap', to: 'public#sitemap'
  get 'terms_of_service', to: 'public#terms_of_service'
  get 'error/not_found', to: 'public/error#not_found'

  namespace :user do
    get 'dashboard'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users_controller/omniauth_callbacks" }
  # resources :users_permissions
  # resources :permissions
  # resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :children, :class_name => Permission.name, :foreign_key => "parent_id"
  belongs_to :parent, :class_name => Permission.name, :foreign_key => "parent_id", optional: true

  #TODO Add breadcrumb methods.

  @@permissions = {
    root: Permission.find_by_name('root'),
    developer: Permission.find_by_name('developer'),
    administrator: Permission.find_by_name('administrator'),
    user: Permission.find_by_name('user'),
    public: Permission.find_by_name('public')
  }.deep_freeze

  def self.permissions
    @@permissions
  end

  def permissions
    @@permissions
  end

  def _sanitize
    super

    if !self.parent.nil?
      self.parent_id = self.parent.id
    end
  end

  def _validate
    super
  end

end

app/controllers/development_controller.rb
class DevelopmentController < ApplicationController
  def dashboard
  end
end

app/controllers/users_permissions_controller.rb
class UsersPermissionsController < ApplicationController
  before_action :set_user_permission, only: [:show, :edit, :update, :destroy]

  # GET /users_permissions
  # GET /users_permissions.json
  def index
    @users_permissions = UserPermission.all
  end

  # GET /users_permissions/1
  # GET /users_permissions/1.json
  def show
  end

  # GET /users_permissions/new
  def new
    @user_permission = UserPermission.new
  end

  # GET /users_permissions/1/edit
  def edit
  end

  # POST /users_permissions
  # POST /users_permissions.json
  def create
    @user_permission = UserPermission.new(user_permission_params)

    respond_to do |format|
      if @user_permission.save
        format.html { redirect_to @user_permission, notice: 'User permission was successfully created.' }
        format.json { render :show, status: :created, location: @user_permission }
      else
        format.html { render :new }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users_permissions/1
  # PATCH/PUT /users_permissions/1.json
  def update
    respond_to do |format|
      if @user_permission.update(user_permission_params)
        format.html { redirect_to @user_permission, notice: 'User permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @user_permission }
      else
        format.html { render :edit }
        format.json { render json: @user_permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users_permissions/1
  # DELETE /users_permissions/1.json
  def destroy
    @user_permission.destroy
    respond_to do |format|
      format.html { redirect_to users_permissions_url, notice: 'User permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user_permission
      @user_permission = UserPermission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_permission_params
      params.require(:user_permission).permit(:user_id, :permission_id, :grant)
    end
end

app/helpers/development_helper.rb
module DevelopmentHelper
end

app/helpers/users_permissions_helper.rb
module UsersPermissionsHelper
end

app/views/development/users_permissions/_form.html.erb
<%= form_for(user_permission) do |f| %>
  <% if user_permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user_permission.errors.count, "error") %> prohibited this user_permission from being saved:</h2>

      <ul>
      <% user_permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %>
    <%= f.text_field :user_id %>
  </div>

  <div class="field">
    <%= f.label :permission_id %>
    <%= f.text_field :permission_id %>
  </div>

  <div class="field">
    <%= f.label :grant %>
    <%= f.text_field :grant %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/development/users_permissions/edit.html.erb
<h1>Editing User Permission</h1>

<%= render 'form', user_permission: @user_permission %>

<%= link_to 'Show', @user_permission %> |
<%= link_to 'Back', users_permissions_path %>

app/views/development/users_permissions/index.html.erb
<h1>Users Permissions</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Permission</th>
      <th>Grant</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users_permissions.each do |user_permission| %>
      <tr>
        <td><%= user_permission.user %></td>
        <td><%= user_permission.permission %></td>
        <td><%= user_permission.grant %></td>
        <td><%= link_to 'Show', user_permission %></td>
        <td><%= link_to 'Edit', edit_user_permission_path(user_permission) %></td>
        <td><%= link_to 'Destroy', user_permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User Permission', new_user_permission_path %>

app/views/development/users_permissions/new.html.erb
<h1>New User Permission</h1>

<%= render 'form', user_permission: @user_permission %>

<%= link_to 'Back', users_permissions_path %>

app/views/development/users_permissions/show.html.erb
<p>
  <strong>User:</strong>
  <%= @user_permission.user %>
</p>

<p>
  <strong>Permission:</strong>
  <%= @user_permission.permission %>
</p>

<p>
  <strong>Grant:</strong>
  <%= @user_permission.grant %>
</p>

<%= link_to 'Edit', edit_user_permission_path(@user_permission) %> |
<%= link_to 'Back', users_permissions_path %>