config/routes.rb
Rails.application.routes.draw do

  root to: "public#landing"

  namespace :administration do
    get 'dashboard'
  end

  namespace :development do
    get 'dashboard'
  end

  get 'about', to: 'public#about'
  get 'careers', to: 'public#careers'
  get 'help', to: 'public#help'
  get 'landing', to: 'public#landing'
  get 'privacy_policy', to: 'public#privacy_policy'
  get 'sitemap', to: 'public#sitemap'
  get 'terms_of_service', to: 'public#terms_of_service'
  get 'error/not_found', to: 'public/error#not_found'

  namespace :user do
    get 'dashboard'
  end

  devise_for :users, :controllers => { :omniauth_callbacks => "users_controller/omniauth_callbacks" }
  # resources :users_permissions
  # resources :permissions
  # resources :users

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/permission.rb
class Permission < ApplicationRecord
  has_many :children, :class_name => Permission.name, :foreign_key => "parent_id"
  belongs_to :parent, :class_name => Permission.name, :foreign_key => "parent_id", optional: true

  #TODO Add breadcrumb methods.

  @@permissions = {
    root: Permission.find_by_name('root'),
    developer: Permission.find_by_name('developer'),
    administrator: Permission.find_by_name('administrator'),
    user: Permission.find_by_name('user'),
    public: Permission.find_by_name('public')
  }.deep_freeze

  def self.permissions
    @@permissions
  end

  def permissions
    @@permissions
  end

  def _sanitize
    super

    if !self.parent.nil?
      self.parent_id = self.parent.id
    end
  end

  def _validate
    super
  end

end

app/controllers/development_controller.rb
class DevelopmentController < ApplicationController
  def dashboard
  end
end

app/controllers/permissions_controller.rb
class PermissionsController < ApplicationController
  before_action :set_permission, only: [:show, :edit, :update, :destroy]

  # GET /permissions
  # GET /permissions.json
  def index
    @permissions = Permission.all
  end

  # GET /permissions/1
  # GET /permissions/1.json
  def show
  end

  # GET /permissions/new
  def new
    @permission = Permission.new
  end

  # GET /permissions/1/edit
  def edit
  end

  # POST /permissions
  # POST /permissions.json
  def create
    @permission = Permission.new(permission_params)

    respond_to do |format|
      if @permission.save
        format.html { redirect_to @permission, notice: 'Permission was successfully created.' }
        format.json { render :show, status: :created, location: @permission }
      else
        format.html { render :new }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /permissions/1
  # PATCH/PUT /permissions/1.json
  def update
    respond_to do |format|
      if @permission.update(permission_params)
        format.html { redirect_to @permission, notice: 'Permission was successfully updated.' }
        format.json { render :show, status: :ok, location: @permission }
      else
        format.html { render :edit }
        format.json { render json: @permission.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /permissions/1
  # DELETE /permissions/1.json
  def destroy
    @permission.destroy
    respond_to do |format|
      format.html { redirect_to permissions_url, notice: 'Permission was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_permission
      @permission = Permission.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def permission_params
      params.require(:permission).permit(:parent_id, :breadcrumb, :name, :description)
    end
end

app/helpers/development_helper.rb
module DevelopmentHelper
end

app/helpers/permissions_helper.rb
module PermissionsHelper
end

app/views/development/permissions/_form.html.erb
<%= form_for(permission) do |f| %>
  <% if permission.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(permission.errors.count, "error") %> prohibited this permission from being saved:</h2>

      <ul>
      <% permission.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :parent_id %>
    <%= f.number_field :parent_id %>
  </div>

  <div class="field">
    <%= f.label :breadcrumb %>
    <%= f.text_field :breadcrumb %>
  </div>

  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>

  <div class="field">
    <%= f.label :description %>
    <%= f.text_field :description %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/development/permissions/edit.html.erb
<h1>Editing Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Show', @permission %> |
<%= link_to 'Back', permissions_path %>

app/views/development/permissions/index.html.erb
<h1>Permissions</h1>

<table>
  <thead>
    <tr>
      <th>Parent</th>
      <th>Breadcrumb</th>
      <th>Name</th>
      <th>Description</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @permissions.each do |permission| %>
      <tr>
        <td><%= permission.parent_id %></td>
        <td><%= permission.breadcrumb %></td>
        <td><%= permission.name %></td>
        <td><%= permission.description %></td>
        <td><%= link_to 'Show', permission %></td>
        <td><%= link_to 'Edit', edit_permission_path(permission) %></td>
        <td><%= link_to 'Destroy', permission, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Permission', new_permission_path %>

app/views/development/permissions/new.html.erb
<h1>New Permission</h1>

<%= render 'form', permission: @permission %>

<%= link_to 'Back', permissions_path %>

app/views/development/permissions/show.html.erb
<p>
  <strong>Parent:</strong>
  <%= @permission.parent_id %>
</p>

<p>
  <strong>Breadcrumb:</strong>
  <%= @permission.breadcrumb %>
</p>

<p>
  <strong>Name:</strong>
  <%= @permission.name %>
</p>

<p>
  <strong>Description:</strong>
  <%= @permission.description %>
</p>

<%= link_to 'Edit', edit_permission_path(@permission) %> |
<%= link_to 'Back', permissions_path %>